blank_issues_enabled: false

contact_links:
  - name: Ask a question
    url: https://github.com/github-community-projects/private-mirrors/discussions/new?category=q-a
    about: Ask a question or start a discussion
