name: Run Jest Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test
